version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo "Installing dependencies..."
        - cd app
        - npm install
    build:
      commands:
        - echo "Building React app..."
        - npm run build
  artifacts:
    baseDirectory: app/build
    files:
      - '**/*'
  cache:
    paths:
      - app/node_modules/**/*
      - node_modules/**/*

